nome = input('Qual é o seu nome? ')
print('Seja bem vindo, ', nome, '!')
diaa = input('Qual seu dia de nascimento? ')
mesa = input('Qual o mês? ')
anoa = input('De que ano? ')
print(nome, 'nasceu em ', diaa, '/', mesa, '/', anoa, '.')
num1 = int(input('Agora, lança um número aí: '))
num2 = int(input('Mais um, pra dar aquela somada básica: '))
print('O resultado é', num1 + num2,'. Fácil.')
